env:
  node: true
  browser: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsForRegex": ["container", "docElements", "watchedState", "element"], linebreak-style }]