- name: Hexlet project check
  uses: hexlet/project-action@release
  with:
    hexlet-id: ${{ secrets.HEXLET_ID }}

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release